### This is the main way to configure the application (other than annotations).
### This file is in Yaml format but you can also configure spring boot using the traditional
### Java properties file format. 

spring.jmx:
   enabled: false

#spring.datasource:
#    driverClassName: org.h2.Driver
#    url: jdbc:h2:mem:bootexample;MODE=MySQL

server:
  port: 8090

#management endpoints on a separate port
management:
  server:
    port: 8091
  endpoints:
    web:
      exposure:
        include: "*"    
#  security:
#    enabled: false # management port is internal only. no need to secure it.

#default project info followed by actual injected pom-specified values.
project:
  name: revenberg-songs
  version: 0.1
  description: Revenberg Songs API
info:
  build:
    artifact: ${project.artifactId}
    name: ${project.name}
    description: ${project.description}
    version: ${project.version}

---
spring: 
  profiles:
    active: dev
  profile: "dev"   
  jpa:  
    database-platform: "org.hibernate.dialect.SQLiteDialect"
    show_sql: true
    open-in-view: false
    generate-ddl: true
    hibernate:
#      hbm2ddl:
#        auto: none
      ddl-auto: update
#      dialect: org.hibernate.dialect.SQLiteDialect
    
  datasource:
    url: "jdbc:sqlite:db/test.db"
    driverClassName: "org.sqlite.JDBC"
    username:
    password:
  servlet:
     multipart:
       max-file-size: 50MB
       max-request-size: 50MB
#---
#spring:
#  profiles: test
#  h2:
#    console:
#      enabled: true
#
  
logging:
  file: song.log
  org.hibernate: INFO

endpoints:
  restart:
    enabled: true